---

pacemaker_hacluster_user_pass: hacluster
stonith_config_name: "ans_clusterfence"

rhel_packages:
  - corosync
  - pcs
  - pacemaker

suse_packages:
  - corosync
  - pcs
  - pacemaker

#Overlay IP
ascs_oip_config_name: "rsc_vip_ascs"
ers_oip_config_name: "rsc_vip_ers"

#FileSystem
sapascs_fs_topology_name: "rsc_fs_ascs"
sapers_fs_topology_name: "rsc_fs_ers"

#Instance
sapascs_config_name: "rsc_ascs"
sapers_config_name: "rsc_ers"